# sensor.py
"""sensor.py - Temperature sensors

This project uses an NTC thermistor in a voltage divider. The sensor class
converts ADC readings to temperature (°C).

Thermistor model used
---------------------
This implementation uses the Vishay "inverse polynomial" (Steinhart-Hart-like)
form generated by Vishay's NTC R/T Calculator for NTCLG100E2103JB:

    x = ln(R / R25)
    1/T(K) = A1 + B1*x + C1*x^2 + D1*x^3
    T(°C) = 1 / (1/T(K)) - 273.15

This 4-term form (includes x^2) tracks the manufacturer curve more accurately
across a wide temperature range than the simple Beta equation (Beta ~ 3977K for
this part, but the polynomial is more precise).

Contract
--------
- read_c() -> float
    Return temperature in °C.

Hardware topology assumed (recommended)
---------------------------------------
    Vref --- R_FIXED ---+--- NTC --- GND
                        |
                       ADC

Then:
    Vadc = Vref * Rntc / (Rfixed + Rntc)
    Rntc = Rfixed * Vadc / (Vref - Vadc)

Noise note
----------
Hardware filtering is allowed and recommended:
- 10 nF .. 100 nF ceramic capacitor from ADC node to GND
This reduces high-frequency noise without affecting the DC temperature reading.
Software averaging provides additional noise reduction.
"""


from machine import ADC
import time
import math

try:
    from machine import idle as _machine_idle
except Exception:
    _machine_idle = None

_ADC_FULL_SCALE_U16 = 65535.0
_EPSILON = 1e-6
_ADC_TEMP_PIN = 26
_ADC_VREF_V = 3.3
_R_FIXED_OHM = 10000.0
_N_AVG = 10
_NTC_INTER_DELAY_MS = 2
_TICKS_MS = getattr(time, "ticks_ms", None)
_TICKS_ADD = getattr(time, "ticks_add", None)
_TICKS_DIFF = getattr(time, "ticks_diff", None)


def _yield_cpu() -> None:
    if _machine_idle is not None:
        try:
            _machine_idle()
        except Exception:
            pass


def _wait_ms_cooperative(delay_ms: int) -> None:
    d = int(delay_ms)
    if d <= 0:
        return
    if callable(_TICKS_MS) and callable(_TICKS_ADD) and callable(_TICKS_DIFF):
        deadline = _TICKS_ADD(_TICKS_MS(), d)
        while _TICKS_DIFF(_TICKS_MS(), deadline) < 0:
            _yield_cpu()
        return
    end = time.time() + (d / 1000.0)
    while time.time() < end:
        _yield_cpu()


def _avg_u16(adc: ADC, n_avg: int, delay_ms: int) -> int:
    """Average multiple ADC samples (u16) with an optional inter-sample delay."""
    n = max(1, int(n_avg))
    dly = max(0, int(delay_ms))
    s = 0
    for _ in range(n):
        s += adc.read_u16()
        if dly:
            _wait_ms_cooperative(dly)
    return int(s / n)


class TemperatureSensor:
    """Interface/base class for temperature sensors."""

    def read_c(self) -> float:
        raise NotImplementedError


class NTCLG100E2103JB(TemperatureSensor):
    """Vishay NTCLG100E2103JB (10k NTC) using Vishay inverse polynomial.

    Coefficients below come from Vishay's NTC R/T Calculator output for
    NTCLG100E2103JB.

    IMPORTANT: ln() is natural logarithm; R is in ohms; T is in Kelvin internally.
    """

    # Reference resistance for the polynomial
    R25_OHM = 10000.0

    # Vishay inverse polynomial coefficients (temperature from resistance):
    # 1/T(K) = A1 + B1*ln(R/R25) + C1*ln(R/R25)^2 + D1*ln(R/R25)^3
    A1 = 0.00335401643468053
    B1 = 0.00025698501802
    C1 = 0.0000026201306709
    D1 = 0.000000063830907998

    def __init__(
        self,
        adc_pin: int = _ADC_TEMP_PIN,
        r_fixed_ohm: float = _R_FIXED_OHM,
        n_avg: int = _N_AVG,
        inter_delay_ms: int = _NTC_INTER_DELAY_MS,
    ):
        self._adc = ADC(adc_pin)
        self._r_fixed = float(r_fixed_ohm)
        self._n_avg = int(n_avg)
        self._dly = int(inter_delay_ms)

        # Numeric guards (prevent division by zero and log() domain issues)
        self._v_eps = _EPSILON
        self._r_eps = _EPSILON

    def _read_voltage_v(self) -> float:
        raw = _avg_u16(self._adc, self._n_avg, self._dly)
        v = (raw * _ADC_VREF_V) / _ADC_FULL_SCALE_U16
        return max(self._v_eps, min(_ADC_VREF_V - self._v_eps, v))

    def _read_resistance_ohm(self) -> float:
        v = self._read_voltage_v()
        r_ntc = self._r_fixed * v / (_ADC_VREF_V - v)
        return max(self._r_eps, r_ntc)

    @classmethod
    def _temp_c_from_resistance_ohm(cls, r_ohm: float) -> float:
        r = float(r_ohm)
        if r <= 0.0:
            return float("nan")

        x = math.log(r / cls.R25_OHM)  # natural log
        inv_t = cls.A1 + (cls.B1 * x) + (cls.C1 * x * x) + (cls.D1 * x * x * x)  # 1/K

        if inv_t <= 0.0:
            return float("nan")

        t_k = 1.0 / inv_t
        return t_k - 273.15

    def read_c(self) -> float:
        r_ntc = self._read_resistance_ohm()
        return self._temp_c_from_resistance_ohm(r_ntc)
